### PR TITLE
Style: Add icons to profile page

### PR DESCRIPTION
**Pull request by chelsabeth**
This PR adds icons to the profile page. I currently have these icons commented out that way we can use them at a later date

Trello: https://trello.com/c/tqLZJ9ny

### CODE REVIEW

**Comment by chelsabeth** [comment]
[Component: Profile](https://trello.com/c/tqLZJ9ny/47-profile)

**Review by locbgiang — DISMISSED** [review]
Good set up for the future.

**Comment by chelsabeth** [comment]
Hey @locbgiang, could you review this again. I am sorry! I decided to also take out the CSS file because it was not needed. Thank you!

**Review by Cireimu — APPROVED** [review]

**Review by imriven — APPROVED** [review]
I like the use of react-icons i will be using this in the future

**Pull request merged**
