### PR TITLE
chore: fix small logo size

### PR DESCRIPTION
**Pull request by imriven**
https://trello.com/c/aH5O7UN5/66-logo-is-small

issue: the logo is small

-should be responsive from 250px up to 3000px. Any smaller or bigger and they're on their own...

### CODE REVIEW

**Comment by imriven** [comment]
[Logo is small! :(](https://trello.com/c/aH5O7UN5/66-logo-is-small)

**Review by Cireimu — CHANGES_REQUESTED** [review]
The logo looks good in mobile display now, just need you to remove the red outline you put around it for development.

**Comment by imriven** [comment]
Just took out red border sorry about that!

**Comment by imriven** [comment]
[chore: take red outline off of logo](https://trello.com/c/JrQky1uU/100-chore-take-red-outline-off-of-logo)

**Review by Cireimu — APPROVED** [review]

**Review by vtopham — APPROVED** [review]
I love it! So much good stuff here.

**Pull request merged**
