### PR TITLE
Style: Style Homepage

### PR DESCRIPTION
**Pull request by chelsabeth**
Added index.css to style the homepage according to the SaverLife style document and finished adding header. 

<Trello>
UX User Story: https://trello.com/c/MxdqmHVi

### CODE REVIEW

**Comment by imriven** [comment]
Code looks clean and easy to read. It's easy to follow. And there's not a lot of repeated code. Looks good!

**Comment by vtopham** [comment]
This looks amazing! I love the choices that have been made with styled-components and reusable components. Keep up the good work!!

**Review by vtopham — APPROVED** [review]
This is great. I love what's happening with styled-components and the reusable header. Excited to see what happens next.

**Review by locbgiang — APPROVED** [review]
GOOD

**Review by imriven — APPROVED** [review]

**Pull request merged**
