### PR TITLE
Feature: Login Page

### PR DESCRIPTION
**Pull request by imriven**
https://trello.com/c/rMg8SZcz/33-login

**Styled Login Component**

- Added in background image
- Responsive from Mobile to Desktop
- Logo Addition
- Changed color of Login Button on Okta Widget

### CODE REVIEW

**Comment by Cireimu** [comment]
[Component: Landing page](https://trello.com/c/vhgpeTCl/49-component-landing-page)

**Comment by imriven** [comment]
[Component: Login](https://trello.com/c/rMg8SZcz/33-component-login)

**Comment by Cireimu** [comment]
Looks good, just have a few notes:

- Curious what the responsiveness you worked on was for, seems like the sizing is upped, but the actual bar and everything is still off a bit for desktop (at least for my 27inch monitor)
- If the navigation responsiveness is being saved for later then I then that's fine, but if not then we'll want to change the styling for the navigation bar, going from hamburger slide menu to something a bit more desktop-friendly before we merge this
- Curious if there's a particular design decision for the white space around the background image is for the login screen, I don't hate it at all, just curious.

Anyways, good job, with getting that login screen looking really good and your code is nice and clean with zero comments and console log!
our desktop view on a 27 inch display

**Comment by imriven** [comment]
Hi Ethan... I'm not sure if that's my component... I must have done something wrong...
image
image
image

Also, there is some extra white space around my container I think we are going to need a reset file for the CSS.
And from my understanding, the nav/hamburger bar isn't going to show up until the user logs in but please correct me if I'm wrong...

**Review by Cireimu — DISMISSED** [review]

**Comment by imriven** [comment]
There was some issue with this branch passing a test. Ethan debugged it and opened a new PR which I renamed.

**Pull request closed without merging**
